import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";
import { formatIdr } from "@/lib/money";
import { orderFinance } from "@/lib/finance";
export default async function Dashboard(){
 await requireAdminPage();
 const [orders,requests,payments,quotations,paid] = await Promise.all([prisma.order.groupBy({by:["orderStatus"],_count:true}),prisma.jastipRequest.groupBy({by:["status"],_count:true}),prisma.payment.groupBy({by:["status"],_count:true}),prisma.quotation.groupBy({by:["status"],_count:true}),prisma.order.findMany({where:{paymentStatus:{in:["VERIFIED","PAID"]},orderStatus:{not:"CANCELLED"}},include:{procurement:true,quotation:true}})]);
 const count=(statuses:string[])=>orders.filter(o=>statuses.includes(o.orderStatus)).reduce((n,o)=>n+o._count,0);
 const totals=paid.map(orderFinance).reduce((a,o)=>({revenue:a.revenue+o.revenue,cost:a.cost+o.cost,profit:a.profit+o.profit,estimated:a.estimated+(o.actual?0:1)}),{revenue:0,cost:0,profit:0,estimated:0});
 const cards=[["Total pesanan",orders.reduce((n,o)=>n+o._count,0),"/admin/orders"],["Menunggu pembayaran",count(["WAITING_PAYMENT"]),"/admin/orders?status=WAITING_PAYMENT"],["Perlu verifikasi",count(["WAITING_VERIFICATION"]),"/admin/payments?status=WAITING_VERIFICATION"],["Pengadaan aktif",count(["PAID","PURCHASING","PURCHASED","CHECKING_ITEM"]),"/admin/procurement"],["Dalam pengiriman",count(["INTERNATIONAL_SHIPPING","ARRIVED_INDONESIA","DOMESTIC_SHIPPING"]),"/admin/orders"],["Selesai",count(["COMPLETED"]),"/admin/orders?status=COMPLETED"]] as const;
 return <div className="space-y-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Ruang kerja Titip Clei</p><h1 className="page-title">Ringkasan bisnis</h1><p className="mt-3 text-muted-foreground">Prioritas pesanan dan hasil usaha dari transaksi yang tercatat.</p></div><Link href="/admin/reports" className="btn-secondary">Lihat laporan</Link></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,href])=><Link key={label} href={href} className="panel hover:border-primary"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></Link>)}</div><section className="panel"><h2 className="text-lg font-semibold">Keuangan pesanan terverifikasi</h2><div className="mt-6 grid gap-6 sm:grid-cols-3">{[["Pendapatan",totals.revenue],["Total biaya",totals.cost],["Laba kotor",totals.profit]].map(([label,value])=><div key={String(label)}><p className="text-sm text-muted-foreground">{String(label)}</p><p className="mt-2 text-2xl font-semibold">{formatIdr(value)}</p></div>)}</div><p className="mt-5 text-xs leading-6 text-muted-foreground">Kode unik tidak dihitung sebagai pendapatan. {totals.estimated} pesanan masih memakai estimasi biaya hingga pembelian dicatat.</p></section><div className="grid gap-6 lg:grid-cols-2"><section className="panel"><h2 className="font-semibold">Request & penawaran</h2><dl className="mt-5 space-y-4">{[["Request baru",requests.find(r=>r.status==="PENDING_REVIEW")?._count||0],["Penawaran terkirim",quotations.find(q=>q.status==="SENT")?._count||0],["Penawaran diterima",quotations.find(q=>q.status==="ACCEPTED")?._count||0]].map(([label,value])=><div key={label} className="flex justify-between"><dt>{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl><Link className="mt-6 inline-block text-primary underline" href="/admin/requests">Review request</Link></section><section className="panel"><h2 className="font-semibold">Pembayaran</h2><dl className="mt-5 space-y-4">{[["Menunggu",["WAITING_PAYMENT","WAITING_VERIFICATION"]],["Terverifikasi",["VERIFIED","PAID"]],["Ditolak",["REJECTED"]]].map(([label,statuses])=><div key={String(label)} className="flex justify-between"><dt>{label}</dt><dd className="font-semibold">{payments.filter(p=>(statuses as string[]).includes(p.status)).reduce((n,p)=>n+p._count,0)}</dd></div>)}</dl><Link className="mt-6 inline-block text-primary underline" href="/admin/payments">Review pembayaran</Link></section></div></div>;
}
