import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";
import { getOrderStatus } from "@/lib/order-status";
import { formatIdr } from "@/lib/money";
export default async function Page({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
 await requireAdminPage(); const {q="",page="1"}=await searchParams;const n=Math.max(1,Number(page)||1);
 const orders=await prisma.order.findMany({where:{paymentStatus:{in:["VERIFIED","PAID"]},orderStatus:{in:["PAID","PURCHASING","PURCHASED","CHECKING_ITEM"]},...(q?{OR:[{orderNumber:{contains:q,mode:"insensitive"}},{productNameSnapshot:{contains:q,mode:"insensitive"}}]}:{})},include:{procurement:true},orderBy:{createdAt:"asc"},take:31,skip:(n-1)*30});
 return <div className="space-y-6"><div><p className="eyebrow">Pembelian sesuai pesanan</p><h1 className="page-title">Pengadaan barang</h1><p className="mt-3 text-muted-foreground">Pesanan terverifikasi yang perlu dibeli atau disiapkan untuk pengiriman.</p></div><form className="flex gap-3"><input name="q" defaultValue={q} className="field max-w-md" placeholder="Cari nomor pesanan atau barang" aria-label="Cari pengadaan" /><button className="btn-primary">Cari</button></form><div className="panel overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Pesanan / barang","Jumlah","Penjual","Biaya pengadaan","Status","Aksi"].map(h=><th key={h} className="border-b p-3">{h}</th>)}</tr></thead><tbody>{orders.slice(0,30).map(o=><tr key={o.id}><td className="border-b p-3"><p className="font-semibold">{o.orderNumber}</p><p className="mt-1 text-muted-foreground">{o.productNameSnapshot}</p></td><td className="border-b p-3">{o.quantity}</td><td className="border-b p-3">{o.procurement?.marketplace||"Belum ditentukan"}<p>{o.procurement?.seller}</p></td><td className="border-b p-3">{o.procurement?formatIdr(o.procurement.totalCost):"Belum dicatat"}</td><td className="border-b p-3">{getOrderStatus(o.orderStatus).label}</td><td className="border-b p-3"><Link className="text-primary underline" href={`/admin/orders/${o.id}#procurement`}>Kelola</Link></td></tr>)}</tbody></table>{!orders.length&&<p className="py-12 text-center text-muted-foreground">Belum ada barang yang perlu dibeli.</p>}</div><div className="flex gap-3">{n>1&&<Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&page=${n-1}`}>Sebelumnya</Link>}{orders.length>30&&<Link className="btn-secondary" href={`?q=${encodeURIComponent(q)}&page=${n+1}`}>Berikutnya</Link>}</div></div>;
}
