import Link from "next/link";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { ProductCard } from "@/components/ProductCard";
export const dynamic = "force-dynamic";
export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const q = (params.q || "").slice(0,120); const page = Math.max(1, Math.min(10000, Number(params.page) || 1));
  const min = Math.max(0, Number(params.min) || 0); const max = Math.max(min, Number(params.max) || 1000000000);
  const where: Prisma.ProductWhereInput = { status: { not: "CLOSED" }, sellingPrice: { gte: min, lte: max }, ...(q ? { name: { contains: q, mode: "insensitive" } } : {}), ...(params.category ? { category: { OR: [{ id: params.category }, { parentId: params.category }] } } : {}) };
  const sorts: Record<string, Prisma.ProductOrderByWithRelationInput> = { newest: { createdAt: "desc" }, popular: { popularity: "desc" }, low: { sellingPrice: "asc" }, high: { sellingPrice: "desc" } };
  const [products, count, categories] = await Promise.all([prisma.product.findMany({ where, include: { category: true }, orderBy: [sorts[params.sort || ""] || sorts.newest, { id: "asc" }], take: 20, skip: (page-1)*20 }), prisma.product.count({ where }), prisma.category.findMany({ orderBy: { name: "asc" } })]);
  const pageLink = (n: number) => `/products?${new URLSearchParams({ ...Object.fromEntries(Object.entries(params).filter((e): e is [string,string] => typeof e[1] === "string")), page: String(n) })}`;
  return <main className="page-wrap"><p className="eyebrow">Katalog pilihan</p><h1 className="page-title">Temukan titipan berikutnya.</h1><p className="mt-3 max-w-xl text-muted-foreground">Produk di katalog adalah contoh barang yang bisa dititip. Kami membelinya dari China setelah pembayaran terverifikasi.</p><form className="panel mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><label className="form-label lg:col-span-2">Cari produk<input name="q" defaultValue={q} placeholder="Nama barang?" className="field mt-2" /></label><label className="form-label">Kategori<select name="category" defaultValue={params.category || ""} className="field mt-2"><option value="">Semua kategori</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-label">Urutkan<select name="sort" defaultValue={params.sort || "newest"} className="field mt-2"><option value="newest">Terbaru</option><option value="popular">Terpopuler</option><option value="low">Harga terendah</option><option value="high">Harga tertinggi</option></select></label><label className="form-label">Harga minimum<input name="min" type="number" min={0} defaultValue={params.min} placeholder="Rp0" className="field mt-2" /></label><label className="form-label">Harga maksimum<input name="max" type="number" min={0} defaultValue={params.max} placeholder="Tanpa batas" className="field mt-2" /></label><div className="flex gap-3 sm:col-span-2 lg:col-span-6"><button className="btn-primary">Terapkan</button><Link href="/products" className="btn-secondary">Reset</Link></div></form><p className="my-5 text-sm text-muted-foreground">{count} produk ditemukan</p>{products.length ? <div className="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 lg:grid-cols-4">{products.map(p => <ProductCard key={p.id} product={p} />)}</div> : <section className="panel py-14 text-center"><h2 className="font-semibold">Belum ada produk yang cocok.</h2><p className="mt-2 text-sm text-muted-foreground">Coba kata kunci lain, atau kirim link barang yang kamu inginkan.</p><Link className="btn-primary mt-5" href="/request">Request barang</Link></section>}<nav aria-label="Halaman katalog" className="mt-8 flex justify-between gap-4">{page>1 ? <Link href={pageLink(page-1)} className="btn-secondary">Sebelumnya</Link> : <span />}<span className="py-3 text-sm">Halaman {page} / {Math.max(1,Math.ceil(count/20))}</span>{page*20<count ? <Link href={pageLink(page+1)} className="btn-secondary">Berikutnya</Link> : <span />}</nav></main>;
}
