"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { formatIdr } from "@/lib/money";
type Product = { id: string; slug: string; name: string; brand: string | null; category: string; imageUrl: string | null; sellingPrice: number; status: string };
type Variant = { id: string; name: string | null; colorName: string | null; size: string | null; model: string | null; priceAdjustment: number; imageUrl: string | null };
export function CatalogOrderForm({ product, selectedVariant }: { product: Product; selectedVariant?: Variant | null; paymentDestination?: { bankName: string; accountNumber: string; accountHolder: string } }) {
  const router = useRouter(); const key = useRef<string | null>(null); const busy = useRef(false);
  const [quantity, setQuantity] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const total = (product.sellingPrice + (selectedVariant?.priceAdjustment || 0)) * quantity;
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy.current) return; busy.current = true; setSaving(true); setError("");
    key.current ??= crypto.randomUUID();
    const fields = Object.fromEntries(new FormData(event.currentTarget));
    try {
      const response = await fetch("/api/orders/catalog", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...fields, productId: product.id, variantId: selectedVariant?.id, checkoutKey: key.current, quantity, termsAccepted: true }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Pesanan gagal dibuat.");
      router.push(`/payment/${data.order.publicToken}`);
    } catch (err) { setError(err instanceof Error ? err.message : "Koneksi terputus. Silakan coba lagi."); }
    finally { busy.current = false; setSaving(false); }
  }
  const fields = [["customerName", "Nama pemesan", "text"], ["customerPhone", "WhatsApp pemesan", "tel"], ["customerEmail", "Email (opsional)", "email"], ["recipientName", "Nama penerima", "text"], ["recipientPhone", "WhatsApp penerima", "tel"], ["province", "Provinsi", "text"], ["city", "Kota / Kabupaten", "text"], ["district", "Kecamatan", "text"], ["postalCode", "Kode pos", "text"]];
  return <main className="page-wrap"><Link href={`/products/${product.slug}`} className="text-sm text-primary">Kembali ke produk</Link><p className="eyebrow mt-6">01 Pesanan / 02 Pembayaran / 03 Verifikasi</p><h1 className="page-title">Konfirmasi pesanan</h1><p className="mt-2 text-muted-foreground">Periksa varian dan alamatmu. Nominal transfer akan tersedia setelah pesanan dibuat.</p><form onSubmit={submit} className="mt-8 grid items-start gap-6 lg:grid-cols-[1fr_340px]"><section className="panel space-y-5"><h2 className="text-lg font-semibold">Data pemesan & pengiriman</h2><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name, label, type]) => <label key={name} className="form-label">{label}<input name={name} type={type} required={name !== "customerEmail"} maxLength={name === "postalCode" ? 5 : 120} pattern={name === "postalCode" ? "[0-9]{5}" : undefined} className="field mt-2" autoComplete={name === "customerEmail" ? "email" : undefined} /></label>)}</div><label className="form-label">Alamat lengkap<textarea name="addressLine" required minLength={10} maxLength={500} placeholder="Jalan, nomor rumah, RT/RW, kelurahan" className="field mt-2 min-h-24" /></label><label className="form-label">Catatan pengiriman (opsional)<textarea name="shippingNote" maxLength={500} className="field mt-2" /></label></section><aside className="panel space-y-5 lg:sticky lg:top-24">{(selectedVariant?.imageUrl || product.imageUrl) && <img src={selectedVariant?.imageUrl || product.imageUrl!} alt={product.name} className="aspect-square w-full rounded-lg object-cover" />}<h2 className="font-semibold">{product.name}</h2><p className="text-sm text-muted-foreground">{[selectedVariant?.colorName, selectedVariant?.size, selectedVariant?.model, selectedVariant?.name].filter(Boolean).join(" / ")}</p><label className="form-label">Jumlah<input type="number" min={1} max={99} value={quantity} onChange={e => setQuantity(Number(e.target.value))} className="field mt-2" required /></label><div className="border-t pt-4"><p className="text-sm text-muted-foreground">Total pesanan</p><p className="text-2xl font-semibold">{formatIdr(total)}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Kode unik Rp1?Rp100 ditambahkan pada tahap pembayaran. Barang dibeli setelah pembayaran diverifikasi.</p></div><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" required className="mt-1.5" /><span>Saya sudah memeriksa alamat dan varian. Saya memahami barang dibeli sesuai pesanan dan estimasi pengiriman akan dikonfirmasi oleh Titip Clei.</span></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button disabled={saving} className="btn-primary w-full">{saving ? "Membuat pesanan?" : "Lanjut ke pembayaran"}</button></aside></form></main>;
}
