"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Values = { marketplace: string; seller: string | null; productUrl: string | null; currency: string; purchasePrice: number; exchangeRate: number; quantity: number; chinaShipping: number; internationalShipping: number; tax: number; additionalCost: number; status: string; purchasedAt: string; externalOrderNumber: string | null; notes: string | null };
export function ProcurementForm({ orderId, quantity, initial }: { orderId: string; quantity: number; initial?: Values }) {
 const router=useRouter();const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if(saving)return;setSaving(true);setMessage("");try { const response=await fetch("/api/admin/procurement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),orderId})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage("Pengadaan berhasil disimpan.");router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Pengadaan gagal disimpan.");}finally{setSaving(false);} }
 return <form onSubmit={submit} className="panel space-y-5"><h2 className="text-lg font-semibold">Catat pembelian dari penjual</h2><p className="text-sm text-muted-foreground">Harga beli per unit dalam mata uang terpilih. Seluruh ongkir, pajak, dan biaya lain dalam IDR.</p><div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Marketplace<select name="marketplace" defaultValue={initial?.marketplace||"Pinduoduo"} className="field mt-2">{["Pinduoduo","Taobao","1688","Shopee China","Other"].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-label">Mata uang<select name="currency" defaultValue={initial?.currency||"CNY"} className="field mt-2"><option>CNY</option><option>IDR</option></select></label>{[["seller","Nama penjual","text"],["productUrl","Link produk","url"],["purchasePrice","Harga beli per unit","number"],["exchangeRate","Kurs IDR per 1 mata uang","number"],["quantity","Jumlah","number"],["chinaShipping","Ongkir lokal China (IDR)","number"],["internationalShipping","Ongkir internasional (IDR)","number"],["tax","Pajak (IDR)","number"],["additionalCost","Biaya tambahan (IDR)","number"],["externalOrderNumber","Nomor pesanan marketplace","text"]].map(([name,label,type])=><label key={name} className="form-label">{label}<input required={type==="number"} min={0} step={type==="number"?"any":undefined} name={name} type={type} defaultValue={String(initial?.[name as keyof Values]??(name==="quantity"?quantity:name==="exchangeRate"?"":type==="number"?0:""))} className="field mt-2" /></label>)}<label className="form-label">Status<select name="status" defaultValue={initial?.status||"PLANNED"} className="field mt-2"><option value="PLANNED">Direncanakan</option><option value="PURCHASED">Sudah dibeli</option><option value="WAITING_SHIPMENT">Menunggu pengiriman</option></select></label><label className="form-label">Tanggal pembelian<input type="date" name="purchasedAt" defaultValue={initial?.purchasedAt} className="field mt-2" /></label></div><label className="form-label">Catatan internal<textarea name="notes" maxLength={2000} defaultValue={initial?.notes||""} className="field mt-2" /></label><p role="status" className="text-sm">{message}</p><button disabled={saving} className="btn-primary">{saving?"Menyimpan?":"Simpan pengadaan"}</button></form>;
}
